/* Generated by the Nim Compiler v1.9.5 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;

function toJSStr(s_33556924) {
  var result_33556925 = null;

    var res_33556966 = newSeq_33556942((s_33556924).length);
    var i_33556967 = 0;
    var j_33556968 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556967 < (s_33556924).length)) break Label2;
          var c_33556969 = s_33556924[i_33556967];
          if ((c_33556969 < 128)) {
          res_33556966[j_33556968] = String.fromCharCode(c_33556969);
          i_33556967 += 1;
          }
          else {
            var helper_33556982 = newSeq_33556942(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556983 = c_33556969.toString(16);
                  if ((((code_33556983) == null ? 0 : (code_33556983).length) == 1)) {
                  helper_33556982.push("%0");;
                  }
                  else {
                  helper_33556982.push("%");;
                  }
                  
                  helper_33556982.push(code_33556983);;
                  i_33556967 += 1;
                  if ((((s_33556924).length <= i_33556967) || (s_33556924[i_33556967] < 128))) {
                  break Label3;
                  }
                  
                  c_33556969 = s_33556924[i_33556967];
                }
            };
++excHandler;
            try {
            res_33556966[j_33556968] = decodeURIComponent(helper_33556982.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556966[j_33556968] = helper_33556982.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556968 += 1;
        }
    };
    if (res_33556966.length < j_33556968) { for (var i = res_33556966.length ; i < j_33556968 ; ++i) res_33556966.push(null); }
               else { res_33556966.length = j_33556968; };
    result_33556925 = res_33556966.join("");

  return result_33556925;

}

function rawEcho() {
          var buf = "";
      for (var i = 0; i < arguments.length; ++i) {
        buf += toJSStr(arguments[i]);
      }
      console.log(buf);
    

  
}
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jscore.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function newSeq_33556942(len_33556944) {
  var result_33556945 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 623;
    F.filename = "system.nim";
    result_33556945 = new Array(len_33556944); for (var i = 0 ; i < len_33556944 ; ++i) { result_33556945[i] = null; }  framePtr = F.prev;

  return result_33556945;

}

function HEX3Aanonymous_654311427() {
  var F = {procname: "jscore_examples_3.:anonymous", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
  framePtr = F;
    F.line = 153;
    F.filename = "jscore.nim";
    rawEcho([77,105,99,114,111,116,97,115,107]);
  framePtr = F.prev;

  
}
var F = {procname: "module jscore_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
framePtr = F;
F.line = 153;
F.filename = "jscore.nim";
queueMicrotask(HEX3Aanonymous_654311427);
framePtr = F.prev;
var F = {procname: "module jscore_examples_3", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_examples_3.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore_group1_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jscore_group1_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/jscore_group1_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
